// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.32.0--rc1
// source: internal/delivery/grpc/games_grpc/games.proto

package games_grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IdGameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdGameRequest) Reset() {
	*x = IdGameRequest{}
	mi := &file_internal_delivery_grpc_games_grpc_games_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdGameRequest) ProtoMessage() {}

func (x *IdGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_delivery_grpc_games_grpc_games_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdGameRequest.ProtoReflect.Descriptor instead.
func (*IdGameRequest) Descriptor() ([]byte, []int) {
	return file_internal_delivery_grpc_games_grpc_games_proto_rawDescGZIP(), []int{0}
}

func (x *IdGameRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GameCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameStart     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=game_start,json=gameStart,proto3" json:"game_start,omitempty"`
	GameTypeId    string                 `protobuf:"bytes,2,opt,name=game_type_id,json=gameTypeId,proto3" json:"game_type_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameCreateRequest) Reset() {
	*x = GameCreateRequest{}
	mi := &file_internal_delivery_grpc_games_grpc_games_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameCreateRequest) ProtoMessage() {}

func (x *GameCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_delivery_grpc_games_grpc_games_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameCreateRequest.ProtoReflect.Descriptor instead.
func (*GameCreateRequest) Descriptor() ([]byte, []int) {
	return file_internal_delivery_grpc_games_grpc_games_proto_rawDescGZIP(), []int{1}
}

func (x *GameCreateRequest) GetGameStart() *timestamppb.Timestamp {
	if x != nil {
		return x.GameStart
	}
	return nil
}

func (x *GameCreateRequest) GetGameTypeId() string {
	if x != nil {
		return x.GameTypeId
	}
	return ""
}

type GameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	GameStart     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=game_start,json=gameStart,proto3" json:"game_start,omitempty"`
	GameTypeId    string                 `protobuf:"bytes,3,opt,name=game_type_id,json=gameTypeId,proto3" json:"game_type_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameRequest) Reset() {
	*x = GameRequest{}
	mi := &file_internal_delivery_grpc_games_grpc_games_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameRequest) ProtoMessage() {}

func (x *GameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_delivery_grpc_games_grpc_games_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameRequest.ProtoReflect.Descriptor instead.
func (*GameRequest) Descriptor() ([]byte, []int) {
	return file_internal_delivery_grpc_games_grpc_games_proto_rawDescGZIP(), []int{2}
}

func (x *GameRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GameRequest) GetGameStart() *timestamppb.Timestamp {
	if x != nil {
		return x.GameStart
	}
	return nil
}

func (x *GameRequest) GetGameTypeId() string {
	if x != nil {
		return x.GameTypeId
	}
	return ""
}

type GameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	GameStart     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=game_start,json=gameStart,proto3" json:"game_start,omitempty"`
	GameTypeId    string                 `protobuf:"bytes,3,opt,name=game_type_id,json=gameTypeId,proto3" json:"game_type_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameResponse) Reset() {
	*x = GameResponse{}
	mi := &file_internal_delivery_grpc_games_grpc_games_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameResponse) ProtoMessage() {}

func (x *GameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_delivery_grpc_games_grpc_games_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameResponse.ProtoReflect.Descriptor instead.
func (*GameResponse) Descriptor() ([]byte, []int) {
	return file_internal_delivery_grpc_games_grpc_games_proto_rawDescGZIP(), []int{3}
}

func (x *GameResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GameResponse) GetGameStart() *timestamppb.Timestamp {
	if x != nil {
		return x.GameStart
	}
	return nil
}

func (x *GameResponse) GetGameTypeId() string {
	if x != nil {
		return x.GameTypeId
	}
	return ""
}

var File_internal_delivery_grpc_games_grpc_games_proto protoreflect.FileDescriptor

const file_internal_delivery_grpc_games_grpc_games_proto_rawDesc = "" +
	"\n" +
	"-internal/delivery/grpc/games_grpc/games.proto\x12\x05games\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x1f\n" +
	"\rIdGameRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"p\n" +
	"\x11GameCreateRequest\x129\n" +
	"\n" +
	"game_start\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tgameStart\x12 \n" +
	"\fgame_type_id\x18\x02 \x01(\tR\n" +
	"gameTypeId\"z\n" +
	"\vGameRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x129\n" +
	"\n" +
	"game_start\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tgameStart\x12 \n" +
	"\fgame_type_id\x18\x03 \x01(\tR\n" +
	"gameTypeId\"{\n" +
	"\fGameResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x129\n" +
	"\n" +
	"game_start\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tgameStart\x12 \n" +
	"\fgame_type_id\x18\x03 \x01(\tR\n" +
	"gameTypeId2\xf4\x01\n" +
	"\fGamesService\x126\n" +
	"\tFetchById\x12\x14.games.IdGameRequest\x1a\x13.games.GameResponse\x12:\n" +
	"\n" +
	"DeleteById\x12\x14.games.IdGameRequest\x1a\x16.google.protobuf.Empty\x124\n" +
	"\x06Update\x12\x12.games.GameRequest\x1a\x16.google.protobuf.Empty\x12:\n" +
	"\x06Create\x12\x18.games.GameCreateRequest\x1a\x16.google.protobuf.EmptyB#Z!internal/delivery/grpc/games_grpcb\x06proto3"

var (
	file_internal_delivery_grpc_games_grpc_games_proto_rawDescOnce sync.Once
	file_internal_delivery_grpc_games_grpc_games_proto_rawDescData []byte
)

func file_internal_delivery_grpc_games_grpc_games_proto_rawDescGZIP() []byte {
	file_internal_delivery_grpc_games_grpc_games_proto_rawDescOnce.Do(func() {
		file_internal_delivery_grpc_games_grpc_games_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_delivery_grpc_games_grpc_games_proto_rawDesc), len(file_internal_delivery_grpc_games_grpc_games_proto_rawDesc)))
	})
	return file_internal_delivery_grpc_games_grpc_games_proto_rawDescData
}

var file_internal_delivery_grpc_games_grpc_games_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_delivery_grpc_games_grpc_games_proto_goTypes = []any{
	(*IdGameRequest)(nil),         // 0: games.IdGameRequest
	(*GameCreateRequest)(nil),     // 1: games.GameCreateRequest
	(*GameRequest)(nil),           // 2: games.GameRequest
	(*GameResponse)(nil),          // 3: games.GameResponse
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 5: google.protobuf.Empty
}
var file_internal_delivery_grpc_games_grpc_games_proto_depIdxs = []int32{
	4, // 0: games.GameCreateRequest.game_start:type_name -> google.protobuf.Timestamp
	4, // 1: games.GameRequest.game_start:type_name -> google.protobuf.Timestamp
	4, // 2: games.GameResponse.game_start:type_name -> google.protobuf.Timestamp
	0, // 3: games.GamesService.FetchById:input_type -> games.IdGameRequest
	0, // 4: games.GamesService.DeleteById:input_type -> games.IdGameRequest
	2, // 5: games.GamesService.Update:input_type -> games.GameRequest
	1, // 6: games.GamesService.Create:input_type -> games.GameCreateRequest
	3, // 7: games.GamesService.FetchById:output_type -> games.GameResponse
	5, // 8: games.GamesService.DeleteById:output_type -> google.protobuf.Empty
	5, // 9: games.GamesService.Update:output_type -> google.protobuf.Empty
	5, // 10: games.GamesService.Create:output_type -> google.protobuf.Empty
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_internal_delivery_grpc_games_grpc_games_proto_init() }
func file_internal_delivery_grpc_games_grpc_games_proto_init() {
	if File_internal_delivery_grpc_games_grpc_games_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_delivery_grpc_games_grpc_games_proto_rawDesc), len(file_internal_delivery_grpc_games_grpc_games_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_delivery_grpc_games_grpc_games_proto_goTypes,
		DependencyIndexes: file_internal_delivery_grpc_games_grpc_games_proto_depIdxs,
		MessageInfos:      file_internal_delivery_grpc_games_grpc_games_proto_msgTypes,
	}.Build()
	File_internal_delivery_grpc_games_grpc_games_proto = out.File
	file_internal_delivery_grpc_games_grpc_games_proto_goTypes = nil
	file_internal_delivery_grpc_games_grpc_games_proto_depIdxs = nil
}
